import react from "@vitejs/plugin-react";
import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { defineConfig } from "vite";
import type { Plugin } from "vite";

// A purely static build (AC-7.2): `vite build` writes client/dist and nothing
// else is needed to run it. There is no dev proxy any more because there is no
// API — the app's data lives in the browser's localStorage, so the dev server and
// a plain static file server behave identically.

/**
 * Emits `dist/sw.js`: the worker in `client/sw.js`, with this build's precache
 * list and cache name prepended.
 *
 * It runs at `closeBundle` rather than `generateBundle` because by then Vite has
 * also copied `public/` — the manifest and the icons — so the precache list can
 * be taken from the directory that is actually going to be served, instead of
 * from a guess about what ends up in it. A file that exists in `dist` and is
 * missing from the precache list is an app that half works offline, and that is
 * the sort of thing nobody notices until they are on a train.
 *
 * Deliberately not `vite-plugin-pwa`. This project has added no runtime or build
 * dependency since Phase 1 (no SQLite driver, no bcrypt, no chart library), and
 * a generated worker is exactly the thing you most need to be able to read when
 * a stale cache is serving last week's app to a user you cannot reach.
 */
function serviceWorker(): Plugin {
  let root = process.cwd();
  let outDir = "dist";
  let base = "/";

  return {
    name: "habit-tracker-service-worker",
    // Dev has no service worker at all, on purpose: a worker caching an app you
    // are in the middle of editing is how "I fixed it but nothing changed"
    // happens. client/src/pwa.ts unregisters any leftover worker in dev.
    apply: "build",

    configResolved(config) {
      root = config.root;
      outDir = config.build.outDir;
      base = config.base;
    },

    closeBundle() {
      const dist = path.resolve(root, outDir);
      const source = fs.readFileSync(path.resolve(root, "sw.js"), "utf8");

      /** Every file in dist, as a path relative to it. */
      const files: string[] = [];
      const walk = (dir: string): void => {
        for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
          const full = path.join(dir, entry.name);
          if (entry.isDirectory()) walk(full);
          else files.push(path.relative(dist, full).split(path.sep).join("/"));
        }
      };
      walk(dist);

      // The worker never precaches itself, and there is no point shipping the
      // 512px icon to the cache — the OS reads it from the network at install
      // time and never again.
      const precache = files
        .filter((file) => file !== "sw.js")
        .filter((file) => !file.startsWith("icons/icon-512") && !file.startsWith("icons/icon-maskable"))
        .sort();

      // The cache name is a hash of the bytes being cached, so a new build is
      // always a new cache and `activate` can drop the old one wholesale.
      const digest = createHash("sha256");
      for (const file of precache) {
        digest.update(file);
        digest.update(fs.readFileSync(path.join(dist, file)));
      }
      const version = digest.digest("hex").slice(0, 12);

      const buildInfo = {
        version,
        shell: `${base}index.html`,
        precache: precache.map((file) => `${base}${file}`),
      };

      const header =
        `// Generated by the service-worker plugin in client/vite.config.ts. Do not edit.\n` +
        `self.__HABIT_TRACKER_BUILD__ = ${JSON.stringify(buildInfo)};\n`;

      fs.writeFileSync(path.join(dist, "sw.js"), header + source);
    },
  };
}

export default defineConfig({
  plugins: [react(), serviceWorker()],
  server: {
    port: 5173,
    strictPort: true,
  },
  build: {
    outDir: "dist",
    emptyOutDir: true,
  },
});
